---

- name: v2 | Install recent setuptools inside virtualenv
  pip: "name=setuptools version=33.1.1 state=present virtualenv={{ cuckoo_virtualenv }}"
## Result 'ImportError: No module named six.moves'
#  pip: "name=setuptools version=34.3.3 state=present virtualenv={{ rekall_virtualenv }}"
  register: pkg_result
  until: pkg_result is success
- name: v2 | Install recent pip inside virtualenv
  pip: "name=pip version=9.0.1 state=present virtualenv={{ cuckoo_virtualenv }}"
  register: pkg_result
  until: pkg_result is success

- name: v2 | Force version for pyrsistent inside virtualenv
  pip:
    name: pyrsistent
    version: 0.16.1
    state: present
    virtualenv: "{{ cuckoo_virtualenv }}"
  register: pkg_result
  until: pkg_result is success
  when: cuckoo_python is not defined or cuckoo_python != 'python3'

- name: v2 | install cuckoo with pip
  pip:
    name: cuckoo
    state: present
    virtualenv: "{{ cuckoo_virtualenv }}"
    virtualenv_python: "{{ cuckoo_python | default('python') }}"
  register: pkg_result
  until: pkg_result is success

## FIXME! fails on second execution: CuckooCriticalError: Unable to bind ResultServer on
##  192.168.56.1:2042 [Errno 99] Cannot assign requested address.
- name: v2 | set cuckoo working directory
  command: "{{ cuckoo_virtualenv }}/bin/cuckoo --cwd {{ cuckoo_cwd }}"
  args:
    creates: "{{ cuckoo_cwd }}/__init__.py"
  become: yes
  become_user: "{{ cuckoo_user }}"
