---

- name: update community signatures
#  command: "{{ cuckoo_installdir }}/utils/community.py -waf creates={{ cuckoo_installdir }}/modules/signatures/network"
  command: "{{ cuckoo_installdir }}/utils/community.py -waf creates={{ cuckoo_installdir }}/analyzer/windows/bin/Procmon.exe"

