---

- name: update community signatures
#  command: "{{ cuckoo_installdir }}/utils/community.py -waf creates={{ cuckoo_installdir }}/modules/signatures/network"
  command: "{{ cuckoo_installdir }}/utils/community.py -waf creates={{ cuckoo_installdir }}/analyzer/windows/bin/Procmon.exe"
  when: cuckoo_release == 'legacy'

- name: download cuckoo signatures
  command: "{{ cuckoo_virtualenv }}/bin/cuckoo community"
  args:
    creates: "{{ cuckoo_cwd }}/signatures/__init__.py"
  become: yes
  become_user: "{{ cuckoo_user }}"
  when: cuckoo_release != 'legacy'

