---

#- fail: msg="This role is only compatible with Ubuntu"
#  when: ansible_distribution != 'Ubuntu'

- name: Include version-specific variables for Ubuntu.
  include_vars: "{{ ansible_distribution }}-{{ ansible_distribution_version }}.yml"
  when: ansible_os_family == 'Debian'
- name: Include version-specific variables for RedHat
  include_vars: "RedHat-{{ ansible_distribution_version.split('.')[0] }}.yml"
  when: ansible_os_family == "RedHat"

- name: install packages dependencies
  package: name={{ item }} state=present
  with_items: "{{ cuckoo_pkg }}"

- name: check role user exists
  user: "name={{ cuckoo_user }} home={{ cuckoo_homedir }}"

- name: git clone cuckoo
  git: repo=https://github.com/cuckoosandbox/cuckoo.git
       dest={{ cuckoo_installdir }}
       version={{ cuckoo_release }}
       update=no

- include: debian.yml
  when: ansible_os_family == 'Debian'

- include: legacy.yml
  when: cuckoo_release == 'legacy'
- include: cuckoo-v2.yml
  when: cuckoo_release != 'legacy'

## https://github.com/lxc/lxd/issues/2507
- name: set capability on tcpdump
  capabilities: path=/usr/sbin/tcpdump capability='cap_net_raw,cap_net_admin=eip' state=present
  when: >
    not (ansible_virtualization_type is defined and
          (ansible_virtualization_type == "lxc" or ansible_virtualization_type == "docker")
        )

#- include: cuckoo-db.yml

## virtualbox normally should be usable in appropriate context. NOK travis currently
- block:
    - include: cuckoo-vbox.yml
      when: cuckoo_use_vbox is defined and cuckoo_use_vbox
    - include: cuckoo-kvm.yml
      when: cuckoo_use_kvm is defined and cuckoo_use_kvm
    - include: cuckoo-xen.yml
      when: cuckoo_use_xen is defined and cuckoo_use_xen
  when: >
    not (ansible_virtualization_type is defined and
          (ansible_virtualization_type == "lxc" or ansible_virtualization_type == "docker")
        )

- include: cuckoo-signatures.yml
- include: cuckoo-fw.yml

